FROM jenkins/jenkins:lts-jdk17

USER root

RUN apt-get update && \
    apt-get install -y docker.io git maven && \
    rm -rf /var/lib/apt/lists/*

RUN usermod -aG docker jenkins

# Installer les plugins Jenkins nécessaires
RUN jenkins-plugin-cli --plugins \
    git \
    workflow-aggregator \
    docker-workflow \
    credentials-binding \
    ssh-agent

USER jenkins

