services:

  postgres:
    image: postgres:15
    container_name: smartlogi-postgres
    environment:
      POSTGRES_DB: smartlogi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    container_name: smartlogi-api
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartlogi_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: simple-secret-key
      JWT_EXPIRATION: 86400000
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    container_name: smartlogi-jenkins
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: >
      sh -c "chmod 666 /var/run/docker.sock || true && 
             /usr/local/bin/jenkins.sh"
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  jenkins_home:
    driver: local
