spring:
  application:
    name: SmartLogi

  datasource:
    url: jdbc:postgresql://localhost:5432/smartlogi_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/v1.0/db.changelog-master.yaml
    enabled: true

server:
  port: 8080

logging:
  level:
    com.smartlogi: DEBUG
    org.hibernate.SQL: DEBUG
