mail.username=test@example.com
mail.password=testpassword
mail.host=smtp.example.com
mail.port=587
mail.protocol=smtp
mail.properties.mail.smtp.auth=true
mail.properties.mail.smtp.starttls.enable=true
